# Schema for the configuration files of the console_logger module.

console_logger.settings:
  type: mapping
  label: 'Console Logger settings'
  mapping:
    blacklist_parameters:
      type: sequence
      label: 'Request parameters to be blacklisted from console output'
      sequence:
        - type: string
          label: 'Parameter name'
    censor_parameters:
      type: sequence
      label: 'Request parameters to be censored from console output'
      sequence:
        - type: string
          label: 'Parameter name'
